language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

    # Catch code formatting issues
    - env: RUSTFMT
      rust: stable
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check

    # Make sure there are no clippy warnings
    - env: CLIPPY
      rust: stable
      install:
        - rustup component add clippy
      script:
        - cargo clippy --all-features --all-targets -- -D warnings
        - cd lexpr-macros && cargo clippy --all-features --all-targets -- -D warnings

  allow_failures:
    - rust: nightly
  fast_finish: true

branches:
  only:
    - master

cache:
  cargo: true
