[package]
name = "serde-lexpr"
description = "Serde support for Lisp S-expressions"
version = "0.2.0"
authors = ["Andreas Rottmann <mail@r0tty.org>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rotty/lexpr-rs"
readme = "README.md"
documentation = "https://docs.rs/serde-lexpr/"
keywords = ["lisp", "s-expression", "sexp", "sexpr", "serde"]
categories = ["encoding", "data-structures", "parser-implementations"]
edition = "2021"
rust-version = "1.56"

[features]
default = []
# Convert tuples to lists `(...)` instead of vectors `#(...)`
tuple_as_list = []

# Convert booleans to `t`/`nil` instead of `#t`/`#f`
bool_as_tnil = []

# Normalize all symbols to lowercase for case-insensitive comparison (serde rename feature(to lowercase) required for enums)
sym_as_lower = []

[dependencies]
lexpr = { version = "0.3.0", path = "../lexpr" }
serde = "1.0.89"

[dev-dependencies]
serde_derive = "1.0.89"
serde_bytes = "0.11"
lexpr = { version = "0.3.0", path = "../lexpr", features = ["sexp-macro"] }
