[package]
name = "msrv-test"
version = "0.0.1"
authors = ["Andreas Rottmann <a.rottmann@gmx.at>"]
edition = "2021"

[dependencies]
lexpr = { path = "../lexpr", features = ["sexp-macro"] }

[workspace]
