on: [pull_request]
name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo check
        run: cargo check --all-features --all-targets --config 'build.warnings="deny"'

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Install ${{ matrix.toolchain }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Run cargo test (default features)
        run: cargo test --all-targets

      - name: Run cargo test (all features)
        run: cargo test --all-features --all-targets

  msrv-check:
    # We require at least Rust 1.71, so we can use a current version
    # of the `proc-macro2` crate, which has an MSRV of 1.71, as of
    # version 1.0.107.
    name: "MSRV (1.71) compile check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Install 1.71 toolchain
        uses: dtolnay/rust-toolchain@1.71

      - name: Run cargo build
        run: cargo build
        working-directory: ./msrv-test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Install ${{ matrix.toolchain }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: "clippy,rustfmt"

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets -- -D warnings
